#!/usr/bin/env python3
"""Regenerate MD/debug.md — verbatim 8-DOF control source snapshot for review."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "MD" / "debug.md"


def _py_files(root: Path) -> list[Path]:
    return sorted(p for p in root.rglob("*.py") if p.is_file() and "__pycache__" not in str(p))


def _collect_sections() -> list[tuple[str, Path]]:
    sections: list[tuple[str, Path]] = []

    for p in _py_files(REPO / "apps" / "joint_admittance_8dof"):
        sections.append((str(p.relative_to(REPO)), p))

    sections.append(("configs/joint_admittance_8dof.yaml", REPO / "configs" / "joint_admittance_8dof.yaml"))

    for p in _py_files(REPO / "rm75_control" / "control" / "admittance_common"):
        sections.append((str(p.relative_to(REPO)), p))

    for p in _py_files(REPO / "rm75_control" / "control" / "joint_admittance_8dof"):
        sections.append((str(p.relative_to(REPO)), p))

    for rel in (
        "rm75_control/core/session.py",
        "rm75_control/force/compensation/tool_pose.py",
        "rm75_control/motion/canfd.py",
    ):
        p = REPO / rel
        if p.is_file():
            sections.append((rel, p))

    asset_dir = REPO / "rm75_control" / "assets" / "robots" / "rm75_6f_8dof"
    for name in (
        "RM75-6F-8dof.urdf",
        "RM75-6F-8dof.collision.urdf",
        "RM75-6F-8dof.genesis.urdf",
        "collision_pairs.yaml",
        "robot.yaml",
    ):
        p = asset_dir / name
        if p.is_file():
            sections.append((str(p.relative_to(REPO)), p))

    for name in sorted(
        (
            "test_8dof_kinematics.py",
            "test_arm_angle_rail_invariance.py",
            "test_bounce_guards.py",
            "test_force_yaml_3n.py",
            "test_adaptive_ke_lateral_gate.py",
            "test_var_damping_adaptation.py",
            "test_phase_ipc.py",
            "test_state_relay.py",
            "test_state_bus.py",
            "test_observer_lockfree.py",
            "test_joint_api.py",
            "test_joint_ik_offline.py",
            "test_rail_nullspace.py",
            "test_rail_extension_task.py",
            "test_rail_scan_replay.py",
            "test_qp_smart_allocation.py",
            "test_srs_e2e_plan_invariants.py",
            "test_srs_ik.py",
            "test_proactive_force_ff.py",
            "test_admittance_contact.py",
            "test_contact_detection.py",
        )
    ):
        p = REPO / "tests" / name
        if p.is_file():
            sections.append((str(p.relative_to(REPO)), p))

    for rel in (
        "scripts/rail_coord_compare.py",
        "scripts/gen_debug_8dof.py",
        "rm75_control/kinematics/srs_ik.py",
    ):
        p = REPO / rel
        if p.is_file():
            sections.append((rel, p))

    # De-duplicate while preserving first occurrence order.
    seen: set[str] = set()
    unique: list[tuple[str, Path]] = []
    for rel, path in sections:
        if rel in seen:
            continue
        seen.add(rel)
        unique.append((rel, path))
    return unique


def lang(path: Path) -> str:
    if path.suffix in (".yaml", ".yml"):
        return "yaml"
    if path.suffix == ".urdf":
        return "xml"
    if path.suffix == ".sh":
        return "bash"
    return "python"


def embed(rel: str, path: Path) -> str:
    body = path.read_text(encoding="utf-8")
    return f"## `{rel}`\n\n```{lang(path)}\n{body}```\n\n"


def header(n_files: int) -> str:
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return (
        "# RM75 8-DOF — Full Source Snapshot (third-party review)\n\n"
        f"Generated: {ts}\n\n"
        "Verbatim copy of all 8-DOF control source. **Do not edit this file** — "
        "edit the originals under the repo.\n\n"
        "Regenerate: `python scripts/gen_debug_8dof.py`\n\n"
        "Included:\n"
        "- `apps/joint_admittance_8dof/` (all `.py`)\n"
        "- `configs/joint_admittance_8dof.yaml`\n"
        "- `rm75_control/control/admittance_common/` (shared admittance / IPC / SHM)\n"
        "- `rm75_control/control/joint_admittance_8dof/` (all `.py`, incl. genesis)\n"
        "- `rm75_control/assets/robots/rm75_6f_8dof/` (URDF + collision yaml)\n"
        "- Supporting: `session.py`, `tool_pose.py`, `canfd.py`\n"
        "- Related tests under `tests/`\n"
        "- `scripts/rail_coord_compare.py`, `rm75_control/kinematics/srs_ik.py`\n\n"
        f"**{n_files} files**\n\n"
        "---\n\n"
    )


def main() -> None:
    sections = _collect_sections()
    missing = [rel for rel, p in sections if not p.is_file()]
    if missing:
        raise SystemExit("missing files:\n  " + "\n  ".join(missing))

    parts = [header(len(sections))]
    for rel, path in sections:
        parts.append(embed(rel, path))
    OUT.write_text("".join(parts), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(sections)} files)")


if __name__ == "__main__":
    main()
