"""RealMan ``control_mode[i]`` values (RM_API2 / develop.realman-robotics.com)."""

from __future__ import annotations

RM_CTRL_FIXED = 0
RM_CTRL_FLOAT = 1
RM_CTRL_SPRING = 2
RM_CTRL_MOTION = 3
RM_CTRL_FORCE_TRACK = 4
RM_CTRL_FLOAT_MOTION = 5
RM_CTRL_SPRING_MOTION = 6
RM_CTRL_FORCE_MOTION = 7
RM_CTRL_ADAPTIVE = 8

FORCE_TRACK_MODES = frozenset({RM_CTRL_FORCE_TRACK, RM_CTRL_FORCE_MOTION, RM_CTRL_ADAPTIVE})
MBK_MODES = frozenset({RM_CTRL_FLOAT, RM_CTRL_SPRING, RM_CTRL_FLOAT_MOTION, RM_CTRL_SPRING_MOTION})
MOTION_MODES = frozenset({RM_CTRL_MOTION, RM_CTRL_FLOAT_MOTION, RM_CTRL_SPRING_MOTION, RM_CTRL_FORCE_MOTION})
